repos:
  # ------------------------
  # Code formatters
  # ------------------------
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.0
    hooks:
      - id: isort
        language_version: python3

  # ------------------------
  # Linter / style
  # ------------------------
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings, pydocstyle]
        language_version: python3
        args: ["--max-line-length=88"]

  # ------------------------
  # checking docstrings
  # ------------------------
  - repo: https://github.com/antonio-murphy/pre-commit-docstrings
    rev: v1.0.3
    hooks:
      - id: check-docstrings
        files: "STL_main/.*\\.py$"
